# Generated by Django 4.0.2 on 2022-02-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('plugin', models.CharField(max_length=500)),
                ('beatmaker', models.CharField(max_length=100)),
                ('explicitcontent', models.BooleanField(default=False)),
            ],
        ),
    ]
