# Generated by Django 4.0.2 on 2022-03-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_sons_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sons',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
