# Generated by Django 4.0.2 on 2022-03-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_sons_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='sons',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sons',
            name='audio_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sons',
            name='duration',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
